### ISSUE TITLE
Feature: Parameterizable Project IDs

### ISSUE THREAD

**Issue by mkarrmann** [waymondo/vscode-todoist#20]
Having the project fixed according to the workspace or user settings doesn't quite work for me for two reasons:

1. It's too limited. I have a handful of projects, and I sometimes want to add a Todo item for one I'm not working on.
2. Many repos include a workspace `.vscode` file for shared, project-level settings. I obviously don't want to commit my todoist project id into a shared repo. VSCode makes this difficult at best to get around.

Users such as me should be able to configure shortcuts to be able to add items to any Todoist project regardless of the VSCode workspace I'm working in. I doubt I'm the only one who has run into these limitations. This can be accomplished simply by making the project id parameterizable.

Here's a fork of this repo where I got this working:

https://github.com/waymondo/vscode-todoist/compare/master...mkarrmann:vscode-todoist:master

If it would be welcomed here, I'm happy to raise a PR here which includes these changes (or a similar change which accomplishes my goal).

**Comment by waymondo** [comment]
Hi there, I'm definitely open to merging a PR that includes commands where you can manually specify which project ID you'd like to open or capture a TODO item for. Please feel free to open a PR

**Comment by mkarrmann** [comment]
@waymondo Great! I got the PR ready, but it seems I don't have access to this repo. When I try to push, I get `fatal: unable to access 'https://github.com/waymondo/vscode-todoist.git/': The requested URL returned error: 403`

**Comment by mkarrmann** [comment]
@waymondo Following up on this. Could I please be added as a Collaborator to the repo (or whatever else would make it easiest to get my change up and merged in)?

**Comment by waymondo** [comment]
Hi there. You can push the changes to a branch on the repo for your account and open a PR there.

**Comment by dubisdev** [comment]
I'm closing this as it seems that was resolved with #21
