### ISSUE TITLE
Must update to last API version

### ISSUE THREAD

**Issue by dubisdev** [waymondo/vscode-todoist#22]
Hi @waymondo 

The API version that the plugin is using has been deprecated. We can update this by using the latest version of the @doist/todoist-api-typescript package (> [v2.0.0 ](https://github.com/Doist/todoist-api-typescript/releases/tag/v2.0.0))

When I have some time I can open a PR.

**Comment by waymondo** [comment]
Thanks for the heads up. I'd gladly defer to you for the maintenance work if you don't mind :)

**Comment by dubisdev** [comment]
Just fixed this.
Sorry, I thought I was working on my fork and committed directly to master.

Just migrated to the new API version, added some docs for the new feature in #21 and updated some deps.
Might we close #20 ?
