### ISSUE TITLE
VSCode URLs not opening (1.50.1 on Mac)

### ISSUE THREAD

**Issue by hooksoft** [waymondo/vscode-todoist#4]
Hi, thanks for this awesome extension - the simple idea of saving tasks with a file link will be a great time saver.
Unfortunately, the way the URLs are currently formatted **isn't working for me**:

`Testing vscode://waymondo.todoist//Users/hook/work/xyz/File.tsx#4`

By editing manually, I noticed that what actually works for opening a certain file at a certain line is:

`Testing vscode://file//Users/hook/work/xyz/File.tsx:4`

I could not find a link format that works with the extension name in the middle, like you use, by the way.

Are you sure this is working for you? I'm on a Mac too. Cheers!

**Comment by neldeles** [comment]
Am encountering the same issue. For anyone looking for a workaround in meantime, I've installed the Highlight and Todo+ extensions to act as a middleman. My workflow is I comment `// TODO: abcde` on my file. Using Todo+, I view my embedded todos. It gives you a link to the file and line. I highlight this and create a Todoist task using `alt + t c`. Attached is a screenshot of how the embedded todos looks like.

<img width="846" alt="Screen Shot 2021-01-23 at 1 24 49 AM" src="https://user-images.githubusercontent.com/14298160/105524338-7c3f7b00-5d1a-11eb-8567-57156b63108a.png">

**Comment by waymondo** [comment]
Sorry for the late reply here - I haven't been using this extension, or VSCode for a while.

@dubisdev - does linking to a text selection as part of a Todoist task work for you in desktop VSCode?

**Comment by dubisdev** [comment]
I work with Windows and it doesn't work here either. I have tested @hooksoft and it seems to work.

> `Testing vscode://file//Users/hook/work/xyz/File.tsx:4`

If it's okay with you, I'll prepare a PR

**Comment by waymondo** [comment]
Sure! Can you also test / ensure that it works for you with [VSCodium](https://vscodium.com/)? I will verify the fix works on both VSCode & VSCodium for macOS once a PR is made.
