### ISSUE TITLE
Externison biscect problem

### ISSUE THREAD

**Issue by METAVar** [waymondo/vscode-todoist#9]
Issue Type: <b>Bug</b>

Extension biscect

Extension version: 0.1.1
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-156-generic
Remote OS version: Linux x64 4.15.0-156-generic
Fetching remote diagnostics for 'SSH: 68.183.90.23' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (2.21GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/I321407/git/assetbase --crash-reporter-id c2bd481f-25dd-4d00-a05f-fb30f3c761e6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 165.22.213.220|
|OS|Linux x64 4.15.0-156-generic|
|CPUs|DO-Regular (2 x 1799)|
|Memory (System)|3.85GB (0.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 68.183.90.23|
|OS|Linux x64 4.15.0-156-generic|
|CPUs|DO-Regular (2 x 2199)|
|Memory (System)|3.85GB (0.27GB free)|
|VM|0%|

Fetching remote diagnostics for 'SSH: 68.183.90.23' failed: Canceled
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by dubisdev** [comment]
Hi @METAVar!

Seems like your VSCode version was too old for using the extension (the plugin is available for VSCode > [1.66](https://github.com/waymondo/vscode-todoist/blob/ed22c9b61111804b7e117ff286566e48d8dc1389/package.json#L13)

Please try it in a new version and, if the problem persists, don't hesitate in opening a new issue

Thank you!
